### ISSUE TITLE
Container directories: installation and read writeable

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#160]
Currently the installation path picks the first container dir in the configuration. This implies that this one is writeable and not very intuitive.

Extend the configuration with a writeable container dir that is used for the installs. This may be a single one? The list of ro containers dirs might remain.

**Comment by marcmo** [comment]
I think it makes sense to have a single writable path for installations, everything else will be too complicated.
Not sure why we need the feature to have multiple registries. What about the uninstallation? for that we also need `write` permissions on the folder. 
would only make sense if we explicitly want to disable messing with some of the installed applications.

**Comment by flxo** [comment]
Superseded by #174
