### ISSUE TITLE
Provide kernel and initrd for firecracker-container initialisation

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#173]
VM init: 
- package generic kernel and `initrd`
- make images available for deployment with NorthCracker

**Comment by pclesr** [comment]
A minimal kernel that supports virtio/vsocks (plus some tracing hooks for ease of debugging) is 9.6Mb. The initrd is 256Mb with an alpine Java VM inside; there is approximately 40Mb free.

**Comment by pclesr** [comment]
I think a resource container will work well here. I am creating a resource container that has the required binaries (firecracker and initially socat, for the first version) as well as the kernel and initrd.

**Comment by flxo** [comment]
Archive fc issues
