### ISSUE TITLE
Prepare an example for running mixed firecracker and pure minijail containers

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#177]
possible scenario:
- start 19 pure minijail containers
- start 1 FC container
- provide results as benchmark

**Comment by pclesr** [comment]
There are at least three classes of benchmark that will be interesting to compare native container and VM perf:
  Network intensive
  startup time
  computationally intensive

I would propose that in addition to 19 + 1, we also do comparisons of the exact same benchmark (of each of the above 3 classes) in both the native container and VM

**Comment by flxo** [comment]
Archive fc issues
