### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#189]
The integration test currently do happy path testing of the examples. Extend it with:

* API Tests
* Stress tests: eg. start/stop in a loop
* Signatures
* Malformed manifests
* Security features
** Signal on seccomp violation
* CGroups
** Verify cgroup settings
** Test cgroup oom
* ...

**Comment by pclesr** [comment]
I would also add:

malformed north.toml
start/stop runtime in a loop (not just a container)

network settings:
I have a container that I am using to verify network namespace functionality that I will check in as part of the network namespace PR. This container can be used as a basis and converted/integrated into the test framework, but it will require running on the real target (I have not tried it on an x86 dev host)

**Comment by flxo** [comment]
Split into #339 and #340
