### ISSUE TITLE
Need logs from minijail after FDs are closed

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#211]
When a process is launched via `minijail_run_internal`(), closes file descriptors that should not be visible to the child. One side-effect of this is that no logging is available after this. This makes debugging and triaging of errors difficult, if not impossible. For now the work-around is to set `flags.close_open_fds` to 0 so that everything is left open, but that only works for debugging

Specifically, if anything goes wrong in `minijail_enter`() (the routine that enters various namespaces), there is no notification in the log. This will make it impossible to triage in the field.

We need some mechanism to log events in the child process up to the point that `execve`() is called on the real target process.

**Comment by flxo** [comment]
The `log_fd` configured for minijail is added to the list of fds that are not closed after the childs fork:

https://github.com/esrlabs/northstar/blob/1cc27ccca6a65c2ba0486995bd30f03f22ef1c02/northstar/src/runtime/minijail.rs#L229
