### ISSUE TITLE
Minijail / rust API linkage error handling

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#214]
This is a note to track how best to handle the error returns from minijail when launching a container.

A process is sandboxed in `north/src/runtime/process/minijail.rs` using
 ```
impl Process {
    pub async fn start()
```
For network namespaces, the setup is done using the parameters specified in the manifest and the `north.toml` file. The namespace itself is joined when the target process is forked, just prior to the `execve`(). 

minijail likes to invoke `die`(), but that is not very helpful. The new namespace routines will only invoke `die`() if a build/compile time error exists (such as an invalid hard-coded macaddr or too long device name). Otherwise, it will log an error via the minijail `warn`() macro and return. 

Note that this does not log everything. Once the FDs have been closed (stdin/out/err) in `minijail_enter`(), logging is lost. This is also not very helpful.

The minijail Rust <--> C wrappers in` minijail/rust/minijail/src/lib.rs` log the errors via Rust mechanisms  `Err(Error::<whatever>)` ; these appear to go to stdout (like when lauching via `nstar` . These are not stored in the log (logcat).  This results in duplicate error logging: once from minijail (to the log) and once to stdout. This can be both helpful (immediate feedback) and confusing (duplicates)

I don't have a solution yet, I am just trying to get clarification on what the correct approach should be.

**Comment by flxo** [comment]
Obsolete since minijail is removed.
