### ISSUE TITLE
Tests should work on target board

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#215]
It is very important that the tests work in the target environment (for example, an ARM board). This means adapting the tests so that they can be executed remotely (over adb, for example). 

The tests should also be adapted so that the paths to binaries can be configured, instead of relying on the directory structure of the build hierarchy. 

Also, the code that compiles and sets up the test should be refactored to make it easier to add containers with different test functionality (for example, testing network functionality).

**Comment by flxo** [comment]
Implemented with https://github.com/esrlabs/northstar/commit/83570bd97b6361227a7dafb0fb50ffca576328ef
