### ISSUE TITLE
Add over-the-wire API version verification for nstar <--> north communication

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#217]
There does not appear to be any version verification between north and `nstar`. This can lead to inconsistencies if one uses an incorrect version of `nstar`.

There should be a protocol check to make sure both sides are running the same version.

Currently, all that happens is that `nstar` prints
`Error: Invalid response
`and exits.

 In the logs there is the message
`09-26 15:45:28.678   562 54512 W north   : Error receiving from socket: IO error: Failed to read frame length of network package`
But nothing that says "Hey you, you are using the incorrect version of nstar, and the OTW protocol changed".

**Comment by flxo** [comment]
Good point. This is annoying. We should add some kind of connect handshake.
