### ISSUE TITLE
Document manifest format

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#223]
(I did not see any issue for this anywhere, feel free to delete if I have missed it).

There is no documentation on the format of the manifest file, except for the excerpt in the main README. As the manifest grows, or has functionality added, it can be difficult to know what the fields are and what are the allowable values.

As a start, I would propose a file in the docs directory that describes the format of the manifest, and the allowable values for each of the fields.

**Comment by flxo** [comment]
Potential tools:

* jsonschema
* openapi

**Comment by flxo** [comment]
Superseded by #426
