### ISSUE TITLE
Runtime startup checks needed

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#243]
It would be very helpful if the runtime would dump more diagnostics on startup when parsing the toml file.

If any path is incorrect, it will often just exit (even with the -d) flag without logging *why* it is exiting.

**Comment by flxo** [comment]
Check the top-level error printing in the example main. Maybe debug printing the error instead of using `Display` helps here. This issues relates to #340 which should check exactly those errors.

**Comment by flxo** [comment]
Runtime checks configured directories with permissions etc. Everything else is a runtime error.
