### ISSUE TITLE
Process termination of child processes: PR_SET_PDEATHSIG

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#266]
We need a test that ensures that all child processes of a container are cleaned up.

For example, if a container spawns 3 processes, upon exit (or nstar stop), we must make sure that all processes are killed.

**Comment by flxo** [comment]
TODO: Create an integration test  that uses `ps` pre and post some start/stop of the runtime and containers. This test should also `SIGKILL` the runtime.

The problem today is that we use [PR_SET_PDEATHSIG](https://man7.org/linux/man-pages/man2/prctl.2.html) in the child processes. But unfortunately this is *not* done by the minijail and island init. The background is that the `clone` happens from a (possibly) short lived thread of the tokio runtime that may be terminated but the thread pool implementation after some timeout. `PR_SET_PDEATHSIG` sends the configured signal upon the termination of the *thread* that cloned and not the process.

**Comment by flxo** [comment]
@inorick As we talked about this yesterday - you may want to have a try

**Comment by inorick** [comment]
Init processes are now cleaned up if the runtime dies (https://github.com/esrlabs/northstar/pull/370)
