### ISSUE TITLE
Error building northstar binary

### ISSUE THREAD

**Issue by thomashoefkens-vw** [esrlabs/northstar#268]
Hi everyone, 

whilst building the northstar binary, the process fails with the following error:

![image](https://user-images.githubusercontent.com/71012278/106251840-c098b280-6215-11eb-8b3a-f2a11b8738fc.png)

Would you know the root cause of the error?
Compiling on darwin.

Thanks
Thomas

**Comment by flxo** [comment]
Hello @thomashoefkens-vw 

Northstar doesn't support Darwin and runs on Linux only. It relies on Linux features which showed up to be to hard to emulate on Darwin (which we tried in the past).

cheers,

Felix

**Comment by thomashoefkens-vw** [comment]
Hi Felix, understood, thanks for that.
