### ISSUE TITLE
Install and uninstalls query the full repository content to search for containers

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#283]
The install and uninstall routines use `State::find_installed_npk` heavily which is a very expensive operation. Instead of going down to the FS the maps in `State` should hold all the information we need to check if a container/resource is present or not.

@marcmo Can you check on this? Think you're active in this area anyway these days..

**Comment by marcmo** [comment]
will do 👍

**Comment by marcmo** [comment]
this probably does not make sense anymore now since we will do the mount at startup differently
