### ISSUE TITLE
nstar connects and reconnects broke with the structopt refactoring

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#297]
With the structopt refactoring the reconnect behaviour of `nstar` broke:

1. If `nstar` is connected and the RT closes the connection nstar displays `disconnected` and doesn't try to reconnect. There should be periodic reconnection attempts.
2. If nstar is started and cannot reach the RT it fails with an error and doesn't try to reconnect.

**Comment by alfonsoros88** [comment]
#299 adds the logic for this. However, I think that the point `2.` sounds like something that would normally be expected.
