### ISSUE TITLE
Npk mksquashfs options contain uid, gid, *and* all-root

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#313]
The combination of the three `mksquashfs` flags  uid, gid, and all-root do not make sense. Currently the file in the squashfs   images are assigned to `uid`, `gid` because the cli arg is *after* `all-root`. Probably the `all-root` flag needs to be removed.

**Comment by inorick** [comment]
I removed the unnecessary `--all-root` flag in #317.
