### ISSUE TITLE
Manifest verification

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#367]
The `serde` code for parsing the manifests is pretty ok but misses some semantic checks:

Uncomplete list of needed checks:

- [x] `env`, `init`, `args` may not not contains any null byte - needs to be convertible to a `CString`
- [x] mount points may not overlap
- [x] `name`, `version`, `uid` and `gid` are mandatory
- [x] `args`, `env` and others are not valid if `init` equals `None`
- [x] croups names must be convertible to `CString`
- [x] `uid` range
- [x] `gid` range
- [x] character range for all items especially `name`

**Comment by flxo** [comment]
See #208

**Comment by inorick** [comment]
Implemented by #387
