### ISSUE TITLE
`nstar exec` subcommand

### ISSUE THREAD

**Issue by rosds** [esrlabs/northstar#454]
This feature enables the execution of additional processes inside a running containers, just like `docker  exec`.

The considered approach will required to extend the interface with the init process running inside each container so that it can be commanded to start new processes. It would also have to keep a record of all the child processes and their respective status.

Each new spawned process will use a separated pseudo-terminal with its master file descriptor sent to the `nstar` client running the `exec` sub-command. The slave part is set to handle the `stdin`, `stdout` and `stderr` of the spawned process.

**Comment by arosds** [comment]
This feature addresses a bit of #212
