### ISSUE TITLE
Any plans to incubate this to CNCF?

### ISSUE THREAD

**Issue by git2g** [esrlabs/northstar#466]
For increased adoption and the possibility of leveraging [other CNCF projects](https://landscape.cncf.io/), you guys have any plans to incubate this on https://contribute.cncf.io ? 

cc - @Thomas Fleischmann (CARIAD)

**Comment by flxo** [comment]
No. Northstar is targeting "embedded" devices - it's not build for the cloud and totally unsuited for such use cases.

**Comment by git2g** [comment]
Well, we were planning to emulate embedded ECUs in the cloud, and the line is blurring these days between "cloud" and "edge". Also looking to see if we could leverage Envoy Proxy to abstract in-vehicle networking. Anyway, there are quite a few CNCF projects that also run in embedded world and vice versa. Northstar is probably one of the few RUST implementations isolating cgroups and namespaces, so it would be good to evolve it for more use cases. Maybe [Linux Foundation](https://www.linuxfoundation.org/projects/hosting/)?

**Comment by flxo** [comment]
There are currently no plans. Closing this until further requirements rise.
