### ISSUE TITLE
squashfs-tools version 4.6 does not exist

### ISSUE THREAD

**Issue by yrjyrj123** [esrlabs/northstar#467]
I searched for squashfs-tools 4.6 according to the README.md, but I found that its latest version is 4.5.

Is it a typo? 

It is recommended to add the download links of the tools you need to the README.md.

https://github.com/plougher/squashfs-tools

**Comment by flxo** [comment]
Hello @yrjyrj123 

Yes that's a typo. Patches are welcome!

cheers,

@flxo
