### ISSUE TITLE
Ruby npk tooling is broken for fs images < 4k (block size)

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#55]
The current ruby hack for creating the verity trees doesn't work for fs images sizes < block size (4k default).
To reproduce take a resource container and remove `root*` - make it empty. The fsimage only contains pseudo files and has exactly 4k block size.

@inorick You have to takle this anyway in your port - so I assigned it to you.

**Comment by inorick** [comment]
Fixed by #175
