### ISSUE TITLE
Termination with uncaught exception of type c10

### ISSUE THREAD

**Issue by PatrickKohl** [esrlabs/northstar#564]
Hi, we got a  uncaught exception of type c10 when we load a AI Model:
![grafik](https://user-images.githubusercontent.com/80391620/162891920-af2f7aff-c9a3-4287-a31a-16a41a4a2f22.png)
We expect that is comes from:
![grafik](https://user-images.githubusercontent.com/80391620/162892043-28b6245f-f8fb-414d-8da8-8ee88c6de2ff.png)

How can we solve this?

**Comment by flxo** [comment]
Hello @PatrickKohl 

Please add some background information: logs, configs and brief description of your problem instead of two screenshots without any context.

Thanks,

@flxo

**Comment by flxo** [comment]
@PatrickKohl Feel free to reopen with more context.
