### ISSUE TITLE
Add possibility to generate northstar keypairs to sextant

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#63]
Northstar uses keys to verify npk packages when they are loaded. npk's get signed using a private key, and they can be verified with a public key.
sextant should allow users to create such keypairs

**Comment by marcmo** [comment]
from @bzld : Related: A feature we don't have currently, but is almost required:
Have a sextant generate_key $NAME command which calls sodiumoxide::crypto::sign::ed25519::gen_keypair() and writes the keys/$NAME.key and keys/$NAME.key.pub files.

**Comment by inorick** [comment]
#151 now allows generating key pairs and saving them to disk.

**Comment by inorick** [comment]
Implemented by #151.
