### ISSUE TITLE
Resource dependencies ignore version

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#67]
When making use of a resource the version is ignored. To be able to respect the version the mount points of *all* containers must be done in a version subdir to allow multiple in parallel e.g `<run_dir>/hello/v0.0.1`. The bind mounts of resources must take care to select the correct version.

**Comment by bzld** [comment]
Related to this: I think having some flexibility regarding version selection here would make a powerful feature:
Maybe supporting sematic versioning expressions in the container manifests and/or a "use latest version of resource container" feature.
That would enable usages like this:
- Resource container contains runtime of some sort - example: Java JRE 11 VM base image, with a (semantic) version of 11.0.4.
- Several (Java application) containers depend on this, but just specify a semver filter of `11.*` to get any Java 11 version of the JRE resource container
- Then the JRE resource container could be updated from 11.0.4 to 11.0.6 and all applications would use the newer Java JRE without needing a new version themselves (unlike the Docker concept where that's not the case!)
