### ISSUE TITLE
NPK utility: inspect, modify and create npk with a cli tool

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#7]
Port the ruby code for packaging npks to rust. Create a lean CLI to
* print the content of npks (in a nice way), e.g manifest only, file list etc...
* allow the manipulation of e.g the manifest (not sure if that is needed)
* pack npks

The clip tool shall operate on a single npk first. Later optionally search for "container" sources and pack. 

Additionally provide a `cargo` extension to plug it into a rust project with manifest meta information from `Cargo.toml`. The workflow could be:
```
cargo new ra
cd ra
cargo npk
<cargo builds>
<cargo outputs a npk>
```

**Comment by bzld** [comment]
Once this is ready, it would be convenient (especially for new people trying out Norhstar) to provide a docker image on Docker hub containing entire the NPK build toolchain (prebuilt rust binaries, correct version of mksquashfs) to pack a provided repository (via bind-mount) to final NPKs (output to bind-mount directory).
Like this maybe:
```docker run -v "`pwd`/repository:/north/repository"  -v "`pwd`/output:/north/output" esrlabs/northstar-pack```

**Comment by flxo** [comment]
This is `sextant` #68

**Comment by inorick** [comment]
Implemented in sextant except for modify. I would go ahead and close this issued unless there is something missing.

**Comment by inorick** [comment]
Implemented in sextant except for modify which will not be implemented.
