### ISSUE TITLE
No access to documentation (google docs) 

### ISSUE THREAD

**Issue by JochenKienzle** [esrlabs/northstar#731]
I can't access the linked google docs page (https://docs.google.com/document/d/1hjmJ2d4Cg74e6yhPf_nqVIOlE0WIAYzwxZL1dQ04rcU/edit?usp=sharing)

Is it intended or replace by something else?

Many thanks in advance

**Comment by flxo** [comment]
Our company decided to shut down gsuite. I moved the document(s) into the repository

Fixed by [0a367da](https://github.com/esrlabs/northstar/commit/0a367da08f9b17ce1078357062d1179bdce27452)
