### ISSUE TITLE
rake example:inspect missing prerequisites

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#76]
rake examples:inspect\[hello_message]
Inpsecting npk with id: hello_message
----------------------------------------------
INFO: Inspecting hello_message-aarch64-unknown-linux-gnu-0.0.1
rake aborted!
Errno::ENOENT: No such file or directory - tree

The requirement for the 'tree' utility should be included in the environment check

**Comment by flxo** [comment]
Obsolete with #68
