### ISSUE TITLE
ESR-01-004 WP1: Possible UB due to struct VerityHeader reordering (Info)

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#788]
During a source code review of the northstar-0.6.0 repository, it was identified that Northstar implements DMVerity super-block structure in Rust on Linux. In the Rust programming language, the compiler is free to reorder structure fields, which can lead to undefined behavior.

**Comment by flxo** [comment]
The struct `VerityHeader` is never used in any FFI context. The block that is append the the verity protected fs is created with [VerityHeader::to_bytes](https://github.com/esrlabs/northstar/blob/e290d9bd42dcc9b5428a208246654b809c7a4b79/northstar-runtime/src/npk/dm_verity.rs#L90). The parsing is done with [VerityHeader::from_bytes](https://github.com/esrlabs/northstar/blob/e290d9bd42dcc9b5428a208246654b809c7a4b79/northstar-runtime/src/npk/dm_verity.rs#L60) (which should be called `from_reader`).

@inorick Can you please double check?

**Comment by inorick** [comment]
The `VerityHeader` is not meant to be compatible with the C struct [1]. Reading and writing is done through the `to_bytes` and `from_bytes` methods that take the padding of the C struct into account.

The alternative would be to mark `VerityHeader` as `#[repr(C, packed)]` and add the `_pad1` and `_pad2` members of [1] to it.
However, this would make access to members of this struct unaligned which is deprecated [2]. As I do not see a security issue with the struct and we have no use case for making it more compatible with C, I suggest we keep it as it is.

[1] https://gitlab.com/cryptsetup/cryptsetup/-/wikis/DMVerity#verity-superblock-format
[2] https://github.com/rust-lang/rust/issues/82523

**Comment by RalfJung** [comment]
>  this would make access to members of this struct unaligned which is deprecated 

Note that *access* to the fields is fine. Only *references* to those fields are a problem.
