### ISSUE TITLE
example musl container fails to build 

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#84]
After doing a rake setup_environment and rake check_environment, the rake build:examples will fail with:
....
cross build --release --bin cpueater --target aarch64-unknown-linux-musl
Unable to find image 'esrlabs/aarch64-unknown-linux-musl:0.2.0' locally
/usr/bin/docker: Error response from daemon: manifest for esrlabs/aarch64-unknown-linux-musl:0.2.0 not found: manifest unknown: manifest unknown.
See '/usr/bin/docker run --help'.
rake aborted!

I believe this is because the docker image is tagged incorrectly:

$ docker image ls --all
REPOSITORY                                                         TAG                                IMAGE ID            CREATED             SIZE
north/aarch64-unknown-linux-musl                                   0.2.0                              ebda4504e805        7 minutes ago       1.34GB
esrlabs/aarch64-unknown-linux-gnu                                  0.2.0                              fd1bb6f93efc        10 days ago         890MB
esrlabs/aarch64-linux-android                                      0.2.0                              e2d59bff3844        10 days ago         2.74GB
north/x86_64-unknown-linux-gnu                                     0.2.0                              f4e91fb8c58d        2 weeks ago         772MB
north/aarch64-unknown-linux-gnu                                    0.2.0                              fd71b8fce7bd        2 weeks ago         891MB

**Comment by marcmo** [comment]
versions where not updated...fixed
