### ISSUE TITLE
Let northstar setup loop-devs on demand

### ISSUE THREAD

**Issue by sebs2837** [esrlabs/northstar#874]
Currently when Northstar mounts a npk it searches for the next free loop-dev and performs a mount.
This is totally fine as long as the number of loop-devs is not limited.
On android-devices the number loop-devices are preconfigured, if more npks are mounted or installed the search for the next free loop-devices can lead to a timeout which subsequently leads to `panic` in the runtime.

As an enhancement the runtime could create new loop-devices on demand.

**Comment by flxo** [comment]
This requires https://github.com/mdaffin/loopdev/pull/56
